import Head from "next/head";
import MdEditor from "@/components/textAreas/MdEditor";
import MdPreview from "@/components/textAreas/MdPreview";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]'>
        <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 min-h-40'>
          {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            MD Editor
          </h1> */}
          <div className='grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8 w-full'>
            <MdEditor />
          </div>
        </div>
      </main>
    </>
  );
}
